# base image
FROM node

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json .
RUN npm install
RUN npm install @vue/cli -g

COPY . .
RUN chown -R node:node .
USER node
# start app
CMD ["npm", "run", "serve"]
