version: '3.8'
services:
  vue:
    container_name: diet-vue
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    working_dir: /app
    ports:
      - '8000:8080'
    volumes:
      - ./client:/app
      - '/app/node_modules'
    restart: unless-stopped
    depends_on:
      - go
      - mysql

  go:
    container_name: diet-api
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    working_dir: /app
    ports:
      - 8001:3000
    volumes:
      - ./server:/app
    restart: unless-stopped
    depends_on:
      - mysql

  maildev:
    image: maildev/maildev
    ports:
      - '8002:1080'
    restart: unless-stopped
    depends_on:
      - go

  mysql:
    container_name: diet-db
    image: mysql
    environment:
      - MYSQL_DATABASE=diet
      - MYSQL_USER=diet
      - MYSQL_PASSWORD=diet
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 5s
      retries: 10
    volumes:
      - diet-data:/var/lib/mysql
    restart: unless-stopped

  next:
    container_name: diet-next
    build:
      context: ./next
      dockerfile: Dockerfile.dev
    working_dir: /app
    ports:
      - '7999:3000'
    volumes:
      - ./next:/app
      - '/app/node_modules'
    restart: unless-stopped
    depends_on:
      - pg

  pg:
    image: postgres
    container_name: diet-pg
    ports:
      - '7998:5432'
    environment:
      - POSTGRES_USER=diet
      - POSTGRES_PASSWORD=diet
      - POSTGRES_DB=diet
    volumes:
      - diet-pg-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  diet-data:
  diet-pg-data:
